apiVersion: v1
entries:
  inlets-http-server:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-24T14:03:35.285732538+01:00"
    description: Helm chart for an inlets HTTP server
    digest: f6de8d04eef6af9c26a17005849f885aece0a5b04117e10ebcd054f5235f9f60
    name: inlets-http-server
    type: application
    urls:
    - https://inlets.github.io/inlets-pro/charts/inlets-http-server-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-24T14:03:35.285258893+01:00"
    description: Helm chart for an inlets HTTP server
    digest: 9c946af21b3fba2710002fc24409b72b43f7377d4f9768109e02213fffcff82a
    name: inlets-http-server
    type: application
    urls:
    - https://inlets.github.io/inlets-pro/charts/inlets-http-server-0.2.1.tgz
    version: 0.2.1
  inlets-pro:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-24T14:03:35.286713767+01:00"
    description: Helm chart for an inlets-pro TCP server
    digest: 108eaf1e75fa15ba60316867c6bdc645f177dbe305bf320382b49fa0e40222db
    name: inlets-pro
    type: application
    urls:
    - https://inlets.github.io/inlets-pro/charts/inlets-pro-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-24T14:03:35.286225036+01:00"
    description: Helm chart for an inlets-pro TCP server
    digest: 75c0ca85be33d6461410332b2d3f9438e681e53a326f0b12cb80540a5b8db0f2
    name: inlets-pro
    type: application
    urls:
    - https://inlets.github.io/inlets-pro/charts/inlets-pro-0.2.1.tgz
    version: 0.2.1
  inlets-pro-client:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-10-24T14:03:35.287568346+01:00"
    description: Helm chart for an inlets-pro TCP client
    digest: db19167e8659dfca115294b51ca8c8cc3ee53e4b4b692ba6ddf3f61a748cdd00
    name: inlets-pro-client
    type: application
    urls:
    - https://inlets.github.io/inlets-pro/charts/inlets-pro-client-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-10-24T14:03:35.287100988+01:00"
    description: Helm chart for an inlets-pro TCP client
    digest: 627dc96ec83d8dd8cff9421d503bd71488a8e276ddbc6c72ec599aa50fd147c0
    name: inlets-pro-client
    type: application
    urls:
    - https://inlets.github.io/inlets-pro/charts/inlets-pro-client-0.2.1.tgz
    version: 0.2.1
generated: "2021-10-24T14:03:35.284504413+01:00"
